[package]
name = "rusty-cnn"
version = "0.1.0"
authors = ["Henri Lunnikivi <henri.lunnikivi@gmail.com>"]

[dependencies]
byteorder = "^1"
env_logger = "^0.5"
log = { version = "^0.4", features = ["release_max_level_info"] }
ocl = "^0.16"
rayon = "^0.9"
lazy_static = "^1.0"

[dev-dependencies]
criterion = { version = "^0.2", features=["real_blackbox"] }
